# Generated by Django 6.0.4 on 2026-05-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("bbox_x1", models.FloatField()),
                ("bbox_y1", models.FloatField()),
                ("bbox_x2", models.FloatField()),
                ("bbox_y2", models.FloatField()),
            ],
        ),
    ]
