# Generated by Django 6.0.4 on 2026-05-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("world", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("bio", models.TextField()),
                ("sprite", models.ImageField(upload_to="sprites/")),
                ("active", models.BooleanField(default=True)),
            ],
        ),
    ]
