# Generated by Django 6.0.4 on 2026-05-10 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("world", "0002_agent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("in_game_time", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-in_game_time"],
            },
        ),
        migrations.CreateModel(
            name="AgentTick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activity", models.TextField()),
                ("inner_thought", models.TextField()),
                ("mood", models.CharField(blank=True, max_length=100)),
                ("raw_prompt", models.TextField(blank=True)),
                ("raw_response", models.TextField(blank=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticks",
                        to="world.agent",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_ticks",
                        to="world.location",
                    ),
                ),
                (
                    "tick",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_states",
                        to="world.tick",
                    ),
                ),
            ],
            options={
                "ordering": ["agent__name"],
                "unique_together": {("agent", "tick")},
            },
        ),
    ]
