# Generated by Django 6.0.4 on 2026-05-11 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("world", "0004_tick_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tick",
            name="active",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="DailyPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("plan", models.JSONField()),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_plans",
                        to="world.agent",
                    ),
                ),
                (
                    "generated_at_tick",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="daily_plans",
                        to="world.tick",
                    ),
                ),
            ],
            options={
                "unique_together": {("agent", "date")},
            },
        ),
    ]
