# Generated by Django 6.0.4 on 2026-05-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("world", "0005_alter_tick_active_dailyplan"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agenttick",
            name="raw_prompt",
        ),
        migrations.RemoveField(
            model_name="agenttick",
            name="raw_response",
        ),
        migrations.AddField(
            model_name="agenttick",
            name="raw_prompts",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="agenttick",
            name="raw_responses",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
