# Generated by Django 6.0.4 on 2026-05-13 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("world", "0006_remove_agenttick_raw_prompt_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Instance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("map_image", models.ImageField(upload_to="maps/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name="location",
            name="slug",
            field=models.SlugField(),
        ),
        migrations.AddField(
            model_name="agent",
            name="instance",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agents",
                to="world.instance",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="instance",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="locations",
                to="world.instance",
            ),
        ),
        migrations.AddField(
            model_name="tick",
            name="instance",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ticks",
                to="world.instance",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="location",
            unique_together={("instance", "slug")},
        ),
    ]
